# Generated by Django 6.0.7 on 2026-10-08 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0003_alter_oportunidade_probabilidade'),
        ('tarefas', '0002_alter_tarefa_oportunidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='oportunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='oportunidades.oportunidade'),
        ),
    ]
