# Generated by Django 6.0.7 on 2026-07-21 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('estrategia', 'Estratégia'), ('financeira', 'Gestão Financeira'), ('processos', 'Processos e Eficiência'), ('rh', 'Gestão de Pessoas'), ('comercial', 'Comercial e Vendas'), ('ti', 'Transformação Digital')], max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('projeto', 'Projeto com Escopo Fechado'), ('horas', 'Banco de Horas'), ('retainer', 'Retainer Mensal'), ('sucesso', 'Fee de Êxito / Performance')], max_length=20)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('horas_estimadas', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('probabilidade', models.PositiveSmallIntegerField(default=0)),
                ('estagio', models.CharField(choices=[('prospeccao', 'Prospecção'), ('qualificacao', 'Qualificação'), ('proposta', 'Proposta Enviada'), ('negociacao', 'Negociação'), ('ganho', 'Ganho'), ('perdido', 'Perdido')], default='prospeccao', max_length=20)),
                ('origem', models.CharField(blank=True, max_length=100)),
                ('data_inicio_prevista', models.DateField(blank=True, null=True)),
                ('duracao_estimada_semanas', models.PositiveIntegerField(blank=True, null=True)),
                ('data_fechamento_real', models.DateField(blank=True, null=True)),
                ('motivo_perda', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('consultor_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to=settings.AUTH_USER_MODEL)),
                ('contato_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.contato')),
                ('empresa_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='clientes.empresacliente')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estagio_anterior', models.CharField(blank=True, choices=[('prospeccao', 'Prospecção'), ('qualificacao', 'Qualificação'), ('proposta', 'Proposta Enviada'), ('negociacao', 'Negociação'), ('ganho', 'Ganho'), ('perdido', 'Perdido')], max_length=20, null=True)),
                ('estagio_novo', models.CharField(choices=[('prospeccao', 'Prospecção'), ('qualificacao', 'Qualificação'), ('proposta', 'Proposta Enviada'), ('negociacao', 'Negociação'), ('ganho', 'Ganho'), ('perdido', 'Perdido')], max_length=20)),
                ('data_mudanca', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='oportunidades.oportunidade')),
            ],
            options={
                'verbose_name': 'Histórico de Estágio',
                'verbose_name_plural': 'Históricos de Estágio',
                'ordering': ['-data_mudanca'],
            },
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['estagio'], name='oportunidad_estagio_f3adfd_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['consultor_responsavel', 'estagio'], name='oportunidad_consult_25a1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['data_fechamento_real'], name='oportunidad_data_fe_87cd4b_idx'),
        ),
    ]
