# Generated by Django 6.0.7 on 2026-08-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='motivo_perda',
            field=models.CharField(blank=True, choices=[('concorrencia', 'Concorrência'), ('preco', 'Preço'), ('prazo', 'Prazo'), ('escopo', 'Escopo inadequado'), ('desinteresse', 'Cliente perdeu interesse')], max_length=30, null=True),
        ),
    ]
