# Generated by Django 6.0.7 on 2026-10-08 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0002_alter_oportunidade_motivo_perda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='probabilidade',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
