# Generated by Django 6.0.7 on 2026-07-23 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oportunidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoConsultoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('andamento', 'Em Andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='nao_iniciado', max_length=20)),
                ('data_inicio_real', models.DateField(blank=True, null=True)),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('horas_estimadas', models.PositiveIntegerField(blank=True, null=True)),
                ('horas_consumidas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('observacoes', models.TextField(blank=True)),
                ('equipe', models.ManyToManyField(blank=True, related_name='projetos', to=settings.AUTH_USER_MODEL)),
                ('gerente_projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_gerenciados', to=settings.AUTH_USER_MODEL)),
                ('oportunidade_origem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='oportunidades.oportunidade')),
            ],
            options={
                'verbose_name': 'Projeto de Consultoria',
                'verbose_name_plural': 'Projetos de Consultoria',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_prevista', models.DateField()),
                ('data_entregue', models.DateField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='projetos.projetoconsultoria')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['data_prevista'],
            },
        ),
        migrations.AddIndex(
            model_name='projetoconsultoria',
            index=models.Index(fields=['status'], name='projetos_pr_status_28281d_idx'),
        ),
        migrations.AddIndex(
            model_name='projetoconsultoria',
            index=models.Index(fields=['gerente_projeto', 'status'], name='projetos_pr_gerente_d9cbff_idx'),
        ),
    ]
