# Generated by Django 6.0.7 on 2026-10-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projetoconsultoria_horas_consumidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetoconsultoria',
            name='status',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('andamento', 'Em Andamento'), ('pausado', 'Pausado'), ('atrasado', 'Atrasado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='nao_iniciado', max_length=20),
        ),
    ]
