# Generated by Django 6.0.7 on 2026-10-09 14:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_projetoconsultoria_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.25')), django.core.validators.MaxValueValidator(Decimal('24'))])),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='projetos.projetoconsultoria')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_horas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lançamento de Horas',
                'verbose_name_plural': 'Lançamentos de Horas',
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['projeto', 'data'], name='projetos_la_projeto_a8732b_idx'), models.Index(fields=['usuario', 'data'], name='projetos_la_usuario_7effbb_idx')],
            },
        ),
    ]
