# Generated by Django 6.0.7 on 2026-10-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_saldo_anterior_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentohoras',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='projetos.entrega', verbose_name='Fase (entrega)'),
        ),
    ]
