# Generated by Django 6.0.7 on 2026-07-23 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_empresacliente_modalidade'),
        ('oportunidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação'), ('email', 'E-mail'), ('reuniao', 'Reunião'), ('whatsapp', 'WhatsApp'), ('visita', 'Visita Presencial'), ('outro', 'Outro')], max_length=20)),
                ('assunto', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_interacao', models.DateTimeField()),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='clientes.contato')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes', to='oportunidades.oportunidade')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'ordering': ['-data_interacao'],
                'abstract': False,
                'indexes': [models.Index(fields=['contato', '-data_interacao'], name='interacoes__contato_539e00_idx'), models.Index(fields=['oportunidade', '-data_interacao'], name='interacoes__oportun_79451d_idx')],
            },
        ),
    ]
