# Generated by Django 6.0.7 on 2026-08-21 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_empresacliente_modalidade'),
        ('interacoes', '0001_initial'),
        ('oportunidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interacao',
            name='interacoes__contato_539e00_idx',
        ),
        migrations.RemoveIndex(
            model_name='interacao',
            name='interacoes__oportun_79451d_idx',
        ),
        migrations.AddIndex(
            model_name='interacao',
            index=models.Index(fields=['contato', 'data_interacao'], name='interacoes__contato_5a17f4_idx'),
        ),
        migrations.AddIndex(
            model_name='interacao',
            index=models.Index(fields=['oportunidade', 'data_interacao'], name='interacoes__oportun_1ec9cb_idx'),
        ),
    ]
