# Generated by Django 6.0.7 on 2026-07-23 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cargo', models.CharField(choices=[('socio', 'Sócio'), ('consultor_senior', 'Consultor Sênior'), ('consultor', 'Consultor'), ('administrativo', 'Administrativo')], default='consultor', max_length=20)),
                ('area_principal', models.CharField(blank=True, choices=[('estrategia', 'Estratégia'), ('financeira', 'Gestão Financeira'), ('processos', 'Processos e Eficiência'), ('rh', 'Gestão de Pessoas'), ('comercial', 'Comercial e Vendas'), ('ti', 'Transformação Digital')], max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['usuario__first_name'],
            },
        ),
    ]
