# Generated by Django 6.0.7 on 2026-07-21 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('setor', models.CharField(blank=True, max_length=100)),
                ('porte', models.CharField(blank=True, choices=[('mei', 'MEI'), ('pequena', 'Pequena'), ('media', 'Média'), ('grande', 'Grande')], max_length=20)),
                ('website', models.URLField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Empresa Cliente',
                'verbose_name_plural': 'Empresas Clientes',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('decisor', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='clientes.empresacliente')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['nome'],
            },
        ),
    ]
