# Generated by Django 6.0.7 on 2026-07-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacliente',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor')], default='vendedor', max_length=20),
        ),
    ]
